author: "Lionheart Software"
author_url: "https://lionheartsw.com"
github_url: "https://github.com/lionheart/LionheartCurrencyTextField"
github_file_prefix: "https://github.com/lionheart/LionheartCurrencyTextField/tree/2.0.2"
xcodebuild_arguments: ["-workspace", "Example/LionheartCurrencyTextField.xcworkspace", "-scheme", "LionheartCurrencyTextField"]
readme: "README.md"
copyright: "&copy; 2016-2017 Lionheart Software LLC"
theme: fullwidth
head: "<style type='text/css'>body { font-family: -apple-system !important; }</style>"

