osx_image: xcode8.3
language: objective-c
script:
- set -o pipefail && xcodebuild test -workspace Example/LionheartCurrencyTextField.xcworkspace -scheme LionheartCurrencyTextField-Example -destination "platform=iOS Simulator,name=iPhone SE,OS=10.3.1" -destination-timeout 1 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
